#!/bin/bash
#echo "Installing Service......"

RABBIT_PASS=cuscs
OS=Ubuntu



if [ $# -eq 0 ]; then
	echo "Usage: install <option> | keystone | glance | nova | nova_start | mysql | mq"
fi


while [ $# -gt 0 ]
 do
   case "$1" in
   keystone)
   		./keystone
   		;;
   keystone_a)
   		echo -e 'y\ny\n' | ./keystone_install
   		;;
   glance)
   		echo -e 'y\ny\n' | ./glance_install
   		;;
   nova)
   		./nova
   		#echo -e 'y\ny\n' | ./nova_install
   		;;
	neutron)
   		./neutron
   		;;
	nova_restart)

   	service nova-api restart
		service nova-cert restart
		service nova-consoleauth restart
		service nova-scheduler restart
		service nova-conductor restart
		service nova-novncproxy restart

		sleep 2

		echo -e "\nVerify......\n"
		nova image-list
		;;
   mq)
		case $OS in
			CentOS)
				echo -e "\nMQ......\n"
				yum install qpid-cpp-server

				sed -i "s/auth=.*/auth=no/g" /etc/qpidd.conf
				grep '^auth' /etc/qpidd.conf

				service qpidd start
				chkconfig qpidd on

				;;
			*)
   				apt-get install rabbitmq-server
   				rabbitmqctl change_password guest $RABBIT_PASS
   				#./mysql_install
   				;;
		esac
   		;;
   mysql)
   		#echo -e 'y\n' | ./mysql_install
   		./mysql create
   		;;
   mysql_config)
   		vi /etc/mysql/my.cnf
   		;;
	esac
	shift
done


