#!/bin/bash
echo "Installing Mysql Service......"

CONTROLLER_IP=10.0.0.11

#ps aux | grep apt
#kill $(ps aux | grep 'mysql csp_build.py' | awk '{print $2}')
#ps aux | grep mysql| awk '{print $2}'
#ps auxf |grep 'm csp_build.py'|`awk '{ print "kill " $2 }'`
#kill -Hup $(ps ux | grep mysql | awk 'NR == 1 {next} {print $2}' | uniq | sort)

apt-get remove --purge mysql-server python-mysqldb
apt-get autoremove --purge mysql-server python-mysqldb
apt-get clean
apt-get install mysql-server python-mysqldb

##	Config File
sed -i "s/bind-address.*/bind-address = $CONTROLLER_IP/g" /etc/mysql/my.cnf 
sed -i "97a default-storage-engine = innodb \ncollation-server = utf8_general_ci \ninit-connect = 'SET NAMES utf8' \ncharacter-set-server = utf8" /etc/mysql/my.cnf



