#!/bin/bash
echo "Installing Mysql Service......"



while [ $# -gt 0 ]
 do
   case "$1" in
   nova)
   		echo -e "Nova......"
   		
   		##	change config
   		sed -i '/connection = .*/d' /etc/nova/nova.conf
		#echo "connection = mysql://nova:cuscs@controller/nova" >> /etc/nova/nova.conf
		echo "sql_connection = mysql://nova:cuscs@controller/nova" >> /etc/nova/nova.conf
		service mysql restart
   		
   		sleep 2
   		
   		mv -f /var/lib/nova/nova.sqlite /var/lib/nova/nova.sqlite.bak
   		mysql -uroot -pcuscs -e "DROP database if exists nova;"
		mysql -uroot -pcuscs -e "CREATE DATABASE nova;"
		mysql -uroot -pcuscs -e "use nova;show tables;"
		mysql -uroot -pcuscs -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY 'cuscs';"
		mysql -uroot -pcuscs -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY 'cuscs';"
		su -s /bin/sh -c "nova-manage db sync" nova
		mysql -uroot -pcuscs -e "use nova;show tables;"
   		;;
   keystone_a)
   		echo -e 'y\ny\n' | ./keystone_install
   		;;
   glance)
   		echo -e 'y\ny\n' | ./glance_install
   		;;
   nova)
   		./nova_install
   		#echo -e 'y\ny\n' | ./nova_install
   		;;
   mq)
   		apt-get install rabbitmq-server
   		#./mysql_install
   		;;
   mysql)
   		echo -e 'y\n' | ./mysql_install
   		#./mysql_install
   		;;
   normal)


#ps aux | grep apt
#kill $(ps aux | grep 'mysql csp_build.py' | awk '{print $2}')
#ps aux | grep mysql| awk '{print $2}'
#ps auxf |grep 'm csp_build.py'|`awk '{ print "kill " $2 }'`
#kill -Hup $(ps ux | grep mysql | awk 'NR == 1 {next} {print $2}' | uniq | sort)


#apt-get --purge remove --auto-remove mysql-server python-mysqldb
apt-get remove --purge mysql-server python-mysqldb
#apt-get install --reinstall mysql-server python-mysqldb
apt-get autoremove --purge mysql-server python-mysqldb
apt-get clean
apt-get install mysql-server python-mysqldb


##	Config File
sed -i 's/bind-address.*/bind-address = 10.0.0.11/g' /etc/mysql/my.cnf 

#sed -i "97a default-storage-engine = innodb collation-server = utf8_general_ci init-connect = 'SET NAMES utf8' character-set-server = utf8" /etc/mysql/my.cnf

#sed -i 's/bind-address/#bind-address/g' /etc/mysql/my.cnf 
#cat mysql.conf >> /etc/mysql/my.cnf 



   		;;
   		esac
	shift
done

