#!/bin/bash

IP_ADDRESS=10.0.0.11
NOVA_DBPASS=cuscs
RABBIT_PASS=cuscs

echo -e "\nInstalling Nova......\n"

source admin-openrc.sh

apt-get --purge remove --auto-remove nova-api nova-cert nova-conductor nova-consoleauth nova-novncproxy nova-scheduler python-novaclient
  
apt-get install nova-api nova-cert nova-conductor nova-consoleauth nova-novncproxy nova-scheduler python-novaclient


##	Config File
#cat nova.conf >> /etc/nova/nova.conf

sed -i '/\[database\]/d' /etc/nova/nova.conf
sed -i '/connection = .*/d' /etc/nova/nova.conf
sed -i '1,16!d' /etc/nova/nova.conf

#sed -i '/rpc_backend = .*/d' /etc/nova/nova.conf
#sed -i '/rabbit_host = .*/d' /etc/nova/nova.conf
#sed -i '/rabbit_password = .*/d' /etc/nova/nova.conf
#
#sed -i '/my_ip = .*/d' /etc/nova/nova.conf
#sed -i '/vncserver_listen = .*/d' /etc/nova/nova.conf
#sed -i '/vncserver_proxyclient_address = .*/d' /etc/nova/nova.conf
#
#sed -i '/auth_strategy = .*/d' /etc/nova/nova.conf
#
#sed -i '/\[keystone_authtoken\]/d' /etc/nova/nova.conf
#sed -i '/auth_uri = .*/d' /etc/nova/nova.conf
#sed -i '/auth_host = .*/d' /etc/nova/nova.conf
#sed -i '/auth_port = .*/d' /etc/nova/nova.conf
#sed -i '/auth_protocol = .*/d' /etc/nova/nova.conf
#sed -i '/admin_tenant_name = .*/d' /etc/nova/nova.conf
#sed -i '/admin_user = .*/d' /etc/nova/nova.conf
#sed -i '/admin_password = .*/d' /etc/nova/nova.conf


#echo -e "\n[database]" >> /etc/nova/nova.conf
sed -i "1i [database]\nconnection = mysql://nova:$NOVA_DBPASS@controller/nova" /etc/nova/nova.conf
#echo -e "\n[database]\nconnection = mysql://nova:$NOVA_DBPASS@controller/nova\n" >> /etc/nova/nova.conf
#echo -e "\nsql_connection = mysql://nova:cuscs@controller/nova" >> /etc/nova/nova.conf

echo -e "rpc_backend = rabbit" >> /etc/nova/nova.conf
echo "rabbit_host = controller" >> /etc/nova/nova.conf
echo "rabbit_password = $RABBIT_PASS" >> /etc/nova/nova.conf

echo -e "my_ip = $IP_ADDRESS" >> /etc/nova/nova.conf
echo -e "vncserver_listen = $IP_ADDRESS" >> /etc/nova/nova.conf
echo -e "vncserver_proxyclient_address = $IP_ADDRESS" >> /etc/nova/nova.conf

echo -e "auth_strategy = keystone" >> /etc/nova/nova.conf

echo -e "[keystone_authtoken]" >> /etc/nova/nova.conf
echo "auth_uri = http://controller:5000" >> /etc/nova/nova.conf
echo "auth_host = controller" >> /etc/nova/nova.conf
echo "auth_port = 35357" >> /etc/nova/nova.conf
echo "auth_protocol = http" >> /etc/nova/nova.conf
echo "admin_tenant_name = service" >> /etc/nova/nova.conf
echo "admin_user = nova" >> /etc/nova/nova.conf
echo "admin_password = cuscs" >> /etc/nova/nova.conf


##	Database
rm -f /var/lib/nova/nova.sqlite

mysql -uroot -pcuscs -e "DROP database if exists nova;"
mysql -uroot -pcuscs -e "CREATE DATABASE nova;"
mysql -uroot -pcuscs -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY 'cuscs';"
mysql -uroot -pcuscs -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY 'cuscs';"

su -s /bin/sh -c "nova-manage db sync" nova



keystone user-delete nova
keystone user-create --name=nova --pass=cuscs --email=jockeyng@hotmail.com
keystone user-role-add --user=nova --tenant=service --role=admin


keystone service-delete nova
keystone service-create --name=nova --type=compute \
  --description="OpenStack Compute"

keystone endpoint-create \
  --service-id=$(keystone service-list | awk '/ compute / {print $2}') \
  --publicurl=http://controller:8774/v2/%\(tenant_id\)s \
  --internalurl=http://controller:8774/v2/%\(tenant_id\)s \
  --adminurl=http://controller:8774/v2/%\(tenant_id\)s

service nova-api restart
service nova-cert restart
service nova-consoleauth restart
service nova-scheduler restart
service nova-conductor restart
service nova-novncproxy restart

sleep 2

echo -e "\nVerify......\n"
nova image-list

echo -e "\n......Nova installed!\n"
